arch:
    max_epochs: 50
model:
    name: 'DSSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
        intrinsic:
            lr: 5e-3
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DSResNet'
        version: '18pt'
        # version: '18n'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
        # version: '18n'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # image_shape: (1024, 1024)
        # image_shape: (512, 512)
        # image_shape: (384, 384)
        # image_shape: (256, 256)
        image_shape: (192, 192)
        # image_shape: (128, 128)
    train:
        batch_size: 16
        dataset: ['Image']
        path: ['/data/datasets/omnicam']
        split: ['{:09}']
        depth_type: ['']
        repeat: [1]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
wandb:
    dry_run: False                   # False means using wandb logging online, True means no wandb logging
    project: 'ucm_euroc'
    dir: '/data/datasets/results'
gpu:
    idx: 1