arch:
    max_epochs: 50
model:
    name: 'EUCMSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
        intrinsic:
            lr: 5e-3
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'EUCMResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (160, 256)
    train:
        batch_size: 16
        dataset: ['PD']
        path: ['/data/datasets/pd_pinhole_euroc']
        split: ['{:09}']
        depth_type: ['vicon']
        repeat: [10]
    validation:
        dataset: ['PD']
        # path: ['/data/datasets/pd_tiny']
        path: ['/data/datasets/pd_pinhole_euroc']
        split: ['{:09}']
        depth_type: ['vicon']
    test:
        dataset: ['PD']
        # path: ['/data/datasets/pd_tiny']
        path: ['/data/datasets/pd_pinhole_euroc']
        split: ['{:09}']
        depth_type: ['vicon']
wandb:
    dry_run: False                   # False means using wandb logging online, True means no wandb logging
    project: 'pd'
    dir: '/data/datasets/results'
gpu:
    idx: 1