arch:
    max_epochs: 50
model:
    name: 'PlumbSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
        intrinsic:
            lr: 1e-3
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PlumbResNet'
        version: '18pt'
        # version: '18n'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
        # version: '18n'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # image_shape: (480, 752)
        image_shape: (256, 384)
        random_hflip: True
        random_vflip: True
        center_crop: False
    train:
        batch_size: 16
        dataset: ['EUROC']
        path: ['/data/datasets/euroc_cam/cam0']
        # path: ['/data/datasets/euroc_MH/cam0']
        # path: ['/data/datasets/euroc/MH_01_easy/mav0/cam0']
        # path: ['/data/datasets/euroc/MH_02_easy/mav0/cam0']
        # path: ['/data/datasets/euroc/MH_03_medium/mav0/cam0']
        # path: ['/data/datasets/euroc/MH_04_difficult/mav0/cam0']
        # path: ['/data/datasets/euroc/MH_05_difficult/mav0/cam0']
        # path: ['/data/datasets/euroc/V1_01_easy/mav0/cam0']
        # path: ['/data/datasets/euroc/V1_02_medium/mav0/cam0']
        # path: ['/data/datasets/euroc/V1_03_difficult/mav0/cam0']
        # path: ['/data/datasets/euroc/V2_01_easy/mav0/cam0']
        # path: ['/data/datasets/euroc/V2_02_medium/mav0/cam0']
        # path: ['/data/datasets/euroc/V2_03_difficult/mav0/cam0']
        # path: ['/data/datasets/euroc_tiny/V1_01_easy/mav0']
        # path: ['/data/datasets/euroc/V1_01_easy_has_depth/mav0']
        forward_context: [49999872]
        back_context: [50000128]
        # forward_context: [249999872]  # for has_depth dataset
        # back_context: [250000128]     # for has_depth dataset
        split: ['{:19}']
        depth_type: ['vicon']
        # repeat: [1]
        repeat: [1]
    validation:
        dataset: ['EUROC']
        # path: ['/data/datasets/euroc/V1_01_easy_has_depth/mav0/']
        path: ['/data/datasets/euroc/V2_01_easy_has_depth/mav0/']
        split: ['{:19}']
        depth_type: ['vicon']
    test:
        dataset: ['EUROC']
        # path: ['/data/datasets/euroc/V1_01_easy_has_depth/mav0']
        path: ['/data/datasets/euroc/V2_01_easy_has_depth/mav0']
        split: ['{:19}']
        depth_type: ['vicon']
wandb:
    dry_run: False                   # False means using wandb logging online, True means no wandb logging
    # dry_run: True
    project: 'ucm_euroc'
    dir: '/data/datasets/results'
gpu:
    idx: 3