model:
    name: 'UCMSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.00009
        pose:
            lr: 0.00009
        intrinsic:
            lr: 1e-3
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'UCMResNet'
        version: '18pt'
    pose_net:
        name: 'PoseNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 200.0
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
        # batch_size: 2
        batch_size: 8
        num_workers: 8
        dataset: ['DGP']
        path: ['/data/datasets/DDAD/ddad.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01']]
        # repeat: [5]
        repeat: [1]
    validation:
        num_workers: 8
        dataset: ['DGP']
        path: ['/data/datasets/DDAD/ddad.json']
        split: ['val']
        depth_type: ['lidar']
        cameras: [['camera_01']]
    test:
        num_workers: 8
        dataset: ['DGP']
        path: ['/data/datasets/DDAD/ddad.json']
        split: ['val']
        depth_type: ['lidar']
        cameras: [['camera_01']]
