arch:
    max_epochs: 50
model:
    name: 'UCMSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
        intrinsic:
            lr: 1e-3
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'UCMResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # image_shape: (2048, 2448)
        # image_shape: (512, 512)
        image_shape: (256, 256)
        random_hflip: False
        random_vflip: False
        random_crop: False
    train:
        batch_size: 16
        dataset: ['GrayImage']
        path: ['/data/datasets/underwater']
        split: ['{:09}']
        depth_type: ['']
        repeat: [10]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
wandb:
    dry_run: False                   # False means using wandb logging online, True means no wandb logging
    # dry_run: True
    project: 'ucm_euroc'
    dir: '/data/datasets/results'
gpu:
    idx: 0
