arch:
    max_epochs: 50
model:
    name: 'UCMSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
        intrinsic:
            lr: 5e-3
    scheduler:
        name: 'StepLR'
        step_size: 10
        gamma: 0.5
    depth_net:
        name: 'EUROCUCMResNet'
        version: '18n'
    pose_net:
        name: 'EUROCPoseResNet'
        version: '18n'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # image_shape: (752, 480)
        image_shape: (256, 384)
    train:
        batch_size: 16
        dataset: ['EUROC']
        # path: ['/data/datasets/euroc_cam/cam0']
        path: ['/data/datasets/euroc/MH_01_easy/mav0/cam0']
        # path: ['/data/datasets/euroc/MH_02_easy/mav0/cam0']
        # path: ['/data/datasets/euroc/MH_03_medium/mav0/cam0']
        # path: ['/data/datasets/euroc/MH_04_difficult/mav0/cam0']
        # path: ['/data/datasets/euroc/MH_05_difficult/mav0/cam0']
        # path: ['/data/datasets/euroc/V1_01_easy/mav0/cam0']
        # path: ['/data/datasets/euroc/V1_02_medium/mav0/cam0']
        # path: ['/data/datasets/euroc/V1_03_difficult/mav0/cam0']
        # path: ['/data/datasets/euroc/V2_01_easy/mav0/cam0']
        # path: ['/data/datasets/euroc/V2_02_medium/mav0/cam0']
        # path: ['/data/datasets/euroc/V2_03_difficult/mav0/cam0']
        forward_context: 49999872
        back_context: 50000128
        split: ['{:19}']
        depth_type: ['']
        repeat: [2]
    validation:
        dataset: ['EUROC']
        path: ['/data/datasets/euroc_tiny/MH_01_easy/mav0/cam0']
        split: ['{:19}']
        depth_type: ['']
    test:
        dataset: ['EUROC']
        path: ['/data/datasets/euroc_tiny/MH_01_easy/mav0/cam0']
        split: ['{:19}']
        depth_type: ['']
