arch:
    max_epochs: 50
model:
    name: 'UCMSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
        intrinsic:
            lr: 5e-3
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'UCMResNet'
        version: '18pt'
        # version: '18n'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
        # version: '18n'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # image_shape: (752, 480)
        # image_shape: (256, 384)
        image_shape: (288, 512)
        random_hflip: True
        random_vflip: True
        center_crop: True
    train:
        # batch_size: 16
        # dataset: ['EUROC', 'EUROC']
        # path: ['/data/datasets/euroc_cam/cam0', '/data/datasets/euroc_cam/cam1']
        # path: ['/data/datasets/euroc_MH/cam0', '/data/datasets/euroc_MH/cam1']
        # split: ['{:19}', '{:19}']
        # forward_context: [49999872, 49999872]
        # back_context: [50000128, 50000128]
        # depth_type: ['vicon', 'vicon']
        # cameras: [['cam0'], ['cam1']]
        # repeat: [1, 1]

        # batch_size: 16
        # dataset: ['EUROC', 'Image']
        # path: ['/data/datasets/euroc_MH/cam0', '/data/datasets/omnicam']
        # split: ['{:19}', '{:09}']
        # forward_context: [49999872, 1]
        # back_context: [50000128, 1]
        # depth_type: ['vicon', '']
        # repeat: [1, 1]

    #     batch_size: 16
    #     dataset: ['EUROC', 'KITTI']
    #     path: ['/data/datasets/euroc_MH/cam0', '/data/datasets/KITTI_raw']
    #     split: ['{:19}', 'data_splits/eigen_zhou_files.txt']
    #     forward_context: [49999872, 1]
    #     back_context: [50000128, 1]
    #     depth_type: ['vicon', 'velodyne']
    #     repeat: [1, 1]
    # validation:
    #     dataset: ['EUROC']
    #     path: ['/data/datasets/euroc/V2_01_easy_has_depth/mav0/']
    #     split: ['{:19}']
    #     depth_type: ['vicon']
    #     cameras: [[]]
    # test:
    #     dataset: ['EUROC']
    #     path: ['/data/datasets/euroc/V2_01_easy_has_depth/mav0']
    #     split: ['{:19}']
    #     depth_type: ['vicon']
    #     cameras: [[]]

        batch_size: 16
        dataset: ['Image', 'KITTI']
        path: ['/data/datasets/gopro', '/data/datasets/KITTI_raw']
        split: ['{:08}', 'data_splits/eigen_zhou_files.txt']
        forward_context: [1, 1]
        back_context: [1, 1]
        depth_type: ['', 'velodyne']
        repeat: [2, 1]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_val_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
wandb:
    dry_run: False                   # False means using wandb logging online, True means no wandb logging
    project: 'ucm_euroc'
    dir: '/data/datasets/results'
gpu:
    idx: 3
